# -*- coding: utf-8 -*-
"""pH와 유분.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSxYx5M5Eviz4IcHTYyJVZObt3cQRluI
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import scipy.stats
from scipy.stats import shapiro
from scipy.stats import levene

!apt-get update -qq
!apt-get install fonts-nanum* -qq

import matplotlib.font_manager as fm
import warnings
warnings.filterwarnings(action='ignore')

path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf' # 나눔 고딕
font_name = fm.FontProperties(fname=path, size=10).get_name() # 기본 폰트 사이즈 : 10
plt.rc('font', family=font_name)

df = pd.read_excel('/content/립밤바른후.xlsx')
df

df = pd.concat([df.iloc[:,2], df.iloc[:, 3]], axis = 1)
df

sns.barplot(data=df)  # x와 y 축에 데이터 지정
plt.ylabel('pH')
plt.rcParams['font.family'] = 'NanumGothic'
plt.show()

# 등분산성 고려
print(levene(df.iloc[:, 0], df.iloc[:, 1]))

scipy.stats.ttest_ind(df.iloc[:, 0], df.iloc[:, 1], equal_var = True)

# 대응표본 t검정 수행
scipy.stats.ttest_rel(df.iloc[:, 0], df.iloc[:, 1])