# -*- coding: utf-8 -*-
"""탄력과 주름.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrRqaQUY57cngwIFPVd5_077PKAjPKyl
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import scipy.stats
from scipy.stats import shapiro
from scipy.stats import levene

df = pd.read_excel('개인별피부탄력.xlsx')
df

sns.barplot(data=df)  # x와 y 축에 데이터 지정
plt.rcParams['font.family'] = 'NanumBarunGothic'
plt.show()

df = pd.concat([df.iloc[:, 1], df.iloc[:, 3]], axis = 1)
df

print(levene(df.iloc[:, 1], df.iloc[:, 3]))
#p-value가 0.05보다 커서 등분산성이 있다고 할 수 있다

scipy.stats.ttest_ind(df.iloc[:, 1], df.iloc[:, 3],  equal_var =True)
#p-value가 유의수준보다 작으므로

df = pd.read_excel('주름측정.xlsx')
df

df = pd.concat([df.iloc[:, 2], df.iloc[:, 3]], axis = 1)
df

sns.barplot(data=df)  # x와 y 축에 데이터 지정
plt.rcParams['font.family'] = 'NanumBarunGothic'
plt.show()

print(levene(df.iloc[:, 0], df.iloc[:, 1]))
#p-value가 0.05보다 커서 등분산성이 있다고 할 수 있다

scipy.stats.ttest_ind(df.iloc[:, 0], df.iloc[:, 1],  equal_var =True)
#p-value가 유의수준보다 작으므로

df = pd.read_excel('미세주름분석.xlsx')
df

df = pd.concat([df.iloc[:,2], df.iloc[:,3]], axis = 1)
df

sns.barplot(data=df)  # x와 y 축에 데이터 지정
plt.rcParams['font.family'] = 'NanumBarunGothic'
plt.show()

print(levene(df.iloc[:, 0], df.iloc[:, 1]))
#p-value가 0.05보다 커서 등분산성이 있다고 할 수 있다

scipy.stats.ttest_ind(df.iloc[:, 0], df.iloc[:, 1],  equal_var =True)
#p-value가 유의수준보다 작으므로